### ISSUE TITLE
Filtro não funciona

### ISSUE THREAD

**Issue by pedrofelipeot** [MatheusPrudente/to-do-list#1]
Poderia me ajudar com meu código? Estou fazendo esse mesmo projeto. Mesmo inserindo o username  e password errados propositalmente, os dados são inseridos no banco de dados. 

package br.com.pedrofelipe.todolist.filter;

import at.favre.lib.crypto.bcrypt.BCrypt;
import br.com.pedrofelipe.todolist.userController.IUserRepository;
import jakarta.servlet.FilterChain;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.Base64;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.web.filter.OncePerRequestFilter;

@Component
public class FilterTaskAuth extends OncePerRequestFilter{
    @Autowired
    private IUserRepository userRepository;
    
    @Override
    protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain filterChain) throws ServletException, IOException {
        var servletPath = request.getServletPath();
            if(servletPath.equals("/tasks")){
                 var authorization = request.getHeader("Authorization");
        var authEncoded = authorization.substring("basic" .length()).trim();
        byte[] authDecode = Base64.getDecoder().decode(authEncoded);
        
        var authString = new String(authDecode);
        String[] credentials = authString.split(":");
        String username = credentials[0];
        String password = credentials[1];
        
        var user = this.userRepository.findByUsername(username);
        if(user==null){
            response.sendError(401);
        } else {
            var passwordVerify = BCrypt.verifyer().verify(password.toCharArray(), user.getPassword());
            if(passwordVerify.verified){
                filterChain.doFilter(request, response);
            }else{
                   response.sendError(401);
            }
        }
            } else{
                 filterChain.doFilter(request, response);
            }
       
        
    
    }
}

**Comment by MatheusPrudente** [comment]
Boa noite @pedrofelipeot, tudo bem?

utilizando seu código como base, pude perceber que a maneira que você verifica a rota "/tasks" permite que adicione novos registros sem necessariamente passar pela autenticação. Afinal a função ```equals()``` verifica se a servletPath é exatamente igual a string definida ("/tasks") para comparação. 

No caso, ao passar uma rota com um id ou até mesmo com um caractere a mais,  a validação para de funcionar corretamente.

**Exemplo** : Ao acessar a rota "/tasks/" consigo inserir um registro no banco sem autenticação , afinal "/tasks/" é uma string diferente de "/tasks". Mesmo que nos dois casos o mesmo controller seja chamado.

**Exemplo 2** : Ao acessar a rota "/tasks/id-exemplo-task" consigo alterar um registro sem autenticação, seguindo o mesmo motivo do exemplo anterior ("/tasks/id-exemplo-task" diferente de "/tasks" ).

Para resolver está situações você pode utilizar a função ```startsWith()``` no lugar do ```equals()```, esta função verifica se a string começa com a string de comparação, que neste caso é "/tasks".  Usando um dos exemplos, ao acessar a rota "/tasks/" preciso me autenticar, pois a rota começa com "/tasks"

Segue o método com a utilização da função startsWith(): 

```Java
@Override
protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain filterChain)
		throws ServletException, IOException {
	var servletPath = request.getServletPath();
	if (servletPath.startsWith("/tasks")) {
		var authorization = request.getHeader("Authorization");
		var authEncoded = authorization.substring("basic".length()).trim();
		byte[] authDecode = Base64.getDecoder().decode(authEncoded);

		var authString = new String(authDecode);
		String[] credentials = authString.split(":");
		String username = credentials[0];
		String password = credentials[1];

		var user = this.userRepository.findByUsername(username);
		if (user == null) {
			response.sendError(401);
		} else {
			var passwordVerify = BCrypt.verifyer().verify(password.toCharArray(), user.getPassword());
			if (passwordVerify.verified) {
				filterChain.doFilter(request, response);
			} else {
				response.sendError(401);
			}
		}
	} else {
		filterChain.doFilter(request, response);
	}
}
```

Espero ter ajudado e bons estudos
